# commit to be tagged for the new release
commit = "HEAD"

project_name = "go-smbios"
github_repo = "talos-systems/go-smbios"
match_deps = "^github.com/(talos-systems/[a-zA-Z0-9-]+)$"

# previous = -
# pre_release = true

# [notes]
